import wx
import analyse #soundanalyse
import Layout as ly  # Layout code generated by wxGlade
import gettext # for localisation shit required by wxGlade
import numpy
import alsaaudio 
import threading 


def set_input_list():
    input_devices_list = get_input_devices()
    for i in input_devices_list :
        frame.input_list.Append(i)
        
    frame.input_list.SetSelection(0)
    print frame.input_list.GetSelection()
    
def get_input_devices ():
        return alsaaudio.pcms(alsaaudio.PCM_CAPTURE)

def show_derivation(pitch):
    #frame.derivation.SetLabel("None")
    if pitch is None:
        frame.derivation.SetLabel("1")


        
def start_stream ():
    inp = alsaaudio.PCM(type= alsaaudio.PCM_CAPTURE, mode=alsaaudio.PCM_NORMAL,device='default')
    inp.setchannels(1)
    inp.setrate(44100)
    inp.setformat(alsaaudio.PCM_FORMAT_S16_LE)
    inp.setperiodsize(1024)
    while True:
            length, data = inp.read()
            samps = numpy.fromstring(data, dtype='int16') 

            pitch = analyse.musical_detect_pitch(samps)          
            wx.CallAfter(show_derivation,pitch)  #CallAfter is necessary for making GUI method calls from non-GUI threads    






if __name__ == "__main__":
    gettext.install("app") 
    
    app = wx.App()
    frame = ly.MainFrame(None, wx.ID_ANY )
    #start code inserting

    set_input_list()
    detect_pitch_thread = threading.Thread(target=start_stream)
    detect_pitch_thread.start()

    #end code inserting
    ########app.SetTopWindow(frame)
    frame.Show()
    app.MainLoop()
    #after app.MainLoop() no code will be executed
    

    

        
    
        


    
    